// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package sqlc

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(title,content,user_id)
  VALUES ($1,$2,$3) RETURNING id, title, content, user_id, created_at, updated_at
`

type CreatePostParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  string `json:"user_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg *CreatePostParams) (*Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Title, arg.Content, arg.UserID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, content, user_id, created_at, updated_at FROM posts WHERE ID=$1
`

func (q *Queries) GetPostByID(ctx context.Context, id int64) (*Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
