// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg *CreatePostParams) (*Post, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetAllPosts(ctx context.Context, dollar_1 interface{}) ([]*Post, error)
	GetAllUsers(ctx context.Context, dollar_1 interface{}) ([]*User, error)
	GetPostByID(ctx context.Context, id int64) (*Post, error)
	GetUserByID(ctx context.Context, id string) (*User, error)
}

var _ Querier = (*Queries)(nil)
