// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg *CreatePostParams) (*Post, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetByID(ctx context.Context, id int64) (*Post, error)
}

var _ Querier = (*Queries)(nil)
