CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE
    IF NOT EXISTS users (
        id VARCHAR(127) PRIMARY KEY DEFAULT gen_random_uuid (),
        username VARCHAR(64) NOT NULL UNIQUE,
        password VARCHAR(60) NOT NULL,
        email citext NOT NULL UNIQUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );