# @format

name: BlogAudit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4
      - name: Verify Dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Vet
        run: go vet ./...
      - name: Static check
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run static check
        run: staticcheck ./...
      - name: Test running
        run: go test -race ./...
